name: Frontend CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'
      - '.github/workflows/csharp-frontend-ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'
      - '.github/workflows/csharp-frontend-ci.yml'

jobs:
  check-frontend:
    name: Check C# Frontend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore './frontend/nuscuties app.sln'

    - name: Check formatting
      run: dotnet format './frontend/nuscuties app.sln' --verify-no-changes --verbosity diagnostic

    - name: Build project
      run: dotnet build './frontend/nuscuties app.sln' --no-restore --verbosity normal
